"""Point cloud export (.ply), written directly rather than through a library.

Binary PLY is a simple enough format that hand-writing it avoids a dependency
and, more usefully, avoids the memory blow-up of building an intermediate object
graph for a cloud with tens of millions of points.
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Optional

import numpy as np

log = logging.getLogger(__name__)


def write_ply(
    path: Path,
    xyz: np.ndarray,
    rgb: Optional[np.ndarray] = None,
    normals: Optional[np.ndarray] = None,
    binary: bool = True,
) -> Path:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    n = len(xyz)

    fields = [("x", "f4"), ("y", "f4"), ("z", "f4")]
    if normals is not None:
        fields += [("nx", "f4"), ("ny", "f4"), ("nz", "f4")]
    if rgb is not None:
        fields += [("red", "u1"), ("green", "u1"), ("blue", "u1")]

    header = ["ply",
              f"format {'binary_little_endian' if binary else 'ascii'} 1.0",
              "comment generated by dronemap",
              f"element vertex {n}"]
    type_names = {"f4": "float", "u1": "uchar"}
    header += [f"property {type_names[t]} {name}" for name, t in fields]
    header += ["end_header"]

    data = np.empty(n, dtype=np.dtype(fields))
    data["x"], data["y"], data["z"] = (xyz[:, i].astype(np.float32) for i in range(3))
    if normals is not None:
        data["nx"], data["ny"], data["nz"] = (normals[:, i].astype(np.float32)
                                              for i in range(3))
    if rgb is not None:
        data["red"], data["green"], data["blue"] = (rgb[:, i].astype(np.uint8)
                                                    for i in range(3))

    with open(path, "wb") as fh:
        fh.write(("\n".join(header) + "\n").encode())
        if binary:
            fh.write(data.tobytes())
        else:
            np.savetxt(fh, np.column_stack([xyz] + ([rgb] if rgb is not None else [])),
                       fmt="%.6f")
    log.info("wrote %s (%d points, %.1f MB)", path, n, path.stat().st_size / 1e6)
    return path


def estimate_normals(xyz: np.ndarray, k: int = 16, viewpoint: Optional[np.ndarray] = None
                     ) -> np.ndarray:
    """PCA normals over a k-NN neighbourhood, oriented toward a viewpoint."""
    from scipy.spatial import cKDTree

    if len(xyz) < k:
        return np.zeros_like(xyz, np.float32)
    tree = cKDTree(xyz)
    _, idx = tree.query(xyz, k=k, workers=-1)
    nbrs = xyz[idx]
    centered = nbrs - nbrs.mean(axis=1, keepdims=True)
    cov = np.einsum("nki,nkj->nij", centered, centered) / k
    # Smallest-eigenvalue direction of the local covariance is the normal.
    _, vecs = np.linalg.eigh(cov)
    normals = vecs[:, :, 0]
    if viewpoint is not None:
        to_view = viewpoint[None, :] - xyz
        flip = np.einsum("ni,ni->n", normals, to_view) < 0
        normals[flip] *= -1.0
    return normals.astype(np.float32)


def voxel_downsample(xyz: np.ndarray, rgb: Optional[np.ndarray], voxel: float):
    """Average points within each voxel. Keeps preview clouds manageable."""
    if voxel <= 0 or len(xyz) == 0:
        return xyz, rgb
    keys = np.floor(xyz / voxel).astype(np.int64)
    _, inverse, counts = np.unique(keys, axis=0, return_inverse=True, return_counts=True)
    inverse = inverse.reshape(-1)
    n_out = len(counts)
    out_xyz = np.zeros((n_out, 3), np.float64)
    np.add.at(out_xyz, inverse, xyz)
    out_xyz /= counts[:, None]
    out_rgb = None
    if rgb is not None:
        acc = np.zeros((n_out, 3), np.float64)
        np.add.at(acc, inverse, rgb.astype(np.float64))
        out_rgb = (acc / counts[:, None]).astype(np.uint8)
    return out_xyz.astype(np.float32), out_rgb
