"""3D Gaussian Splatting export.

Two outputs, both from the same seeded gaussians:

* ``.ply`` in the INRIA 3DGS convention -- the format every 3DGS trainer and
  viewer reads, with SH degree-0 colour and log-scale / quaternion attributes.
* ``.splat`` -- the compact 32-byte-per-splat binary the web viewers use.

These are **seeds**, not trained gaussians. Each surface point becomes a small
disc oriented to the local surface normal, which renders as a reasonable point
cloud and, more importantly, is exactly the initialisation a 3DGS optimizer
wants -- far better than the random or SfM-sparse init most pipelines start from.
Training itself is a post-session GPU job; see `docs/TUNING.md`.
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Optional

import numpy as np

log = logging.getLogger(__name__)

#: Degree-0 spherical harmonic basis constant, C0 = 0.5 * sqrt(1/pi).
SH_C0 = 0.28209479177387814


def rgb_to_sh0(rgb: np.ndarray) -> np.ndarray:
    """uint8 colour -> degree-0 SH coefficient, the 3DGS convention."""
    return (rgb.astype(np.float32) / 255.0 - 0.5) / SH_C0


def normals_to_quaternions(normals: np.ndarray) -> np.ndarray:
    """Rotations taking +z onto each normal, as (w, x, y, z) quaternions.

    A splat's local z is its thin axis, so aligning z with the surface normal
    makes each gaussian a disc lying in the surface -- the right shape for a
    surface element, and a much better optimizer starting point than an
    isotropic blob.
    """
    n = normals / np.maximum(np.linalg.norm(normals, axis=1, keepdims=True), 1e-12)
    z = np.array([0.0, 0.0, 1.0])
    axis = np.cross(np.broadcast_to(z, n.shape), n)
    axis_norm = np.linalg.norm(axis, axis=1)
    dot = np.clip(n @ z, -1.0, 1.0)
    angle = np.arccos(dot)

    quat = np.zeros((len(n), 4), np.float32)
    quat[:, 0] = 1.0  # identity default
    ok = axis_norm > 1e-8
    if ok.any():
        a = axis[ok] / axis_norm[ok, None]
        half = angle[ok] * 0.5
        quat[ok, 0] = np.cos(half)
        quat[ok, 1:] = a * np.sin(half)[:, None]
    # Antiparallel case: any axis perpendicular to z gives a 180-degree flip.
    flipped = (~ok) & (dot < 0)
    if flipped.any():
        quat[flipped] = np.array([0.0, 1.0, 0.0, 0.0], np.float32)
    return quat


def build_gaussians(
    xyz: np.ndarray,
    rgb: np.ndarray,
    normals: Optional[np.ndarray] = None,
    voxel_size: float = 0.04,
    thickness_ratio: float = 0.25,
    opacity: float = 0.85,
):
    """Seed one gaussian per surface point, sized to the voxel resolution."""
    n = len(xyz)
    radius = max(voxel_size, 1e-4) * 0.6
    scales = np.full((n, 3), radius, np.float32)
    scales[:, 2] = radius * thickness_ratio  # flatten along the normal
    if normals is None:
        quats = np.tile(np.array([1.0, 0.0, 0.0, 0.0], np.float32), (n, 1))
    else:
        quats = normals_to_quaternions(normals)
    return {
        "xyz": xyz.astype(np.float32),
        # 3DGS stores log-scale and logit-opacity; the trainer applies exp and
        # sigmoid, so seeds must be written in that same parameterisation.
        "scales_log": np.log(np.maximum(scales, 1e-8)).astype(np.float32),
        "rotations": quats.astype(np.float32),
        "opacity_logit": np.full((n, 1), float(np.log(opacity / (1 - opacity))), np.float32),
        "sh0": rgb_to_sh0(rgb),
        "rgb": rgb.astype(np.uint8),
        "scales": scales,
    }


def write_splat_ply(path: Path, g: dict) -> Path:
    """INRIA-convention 3DGS .ply (binary little-endian)."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    n = len(g["xyz"])

    names = ["x", "y", "z", "nx", "ny", "nz",
             "f_dc_0", "f_dc_1", "f_dc_2", "opacity",
             "scale_0", "scale_1", "scale_2",
             "rot_0", "rot_1", "rot_2", "rot_3"]
    dtype = np.dtype([(nm, "f4") for nm in names])
    data = np.zeros(n, dtype=dtype)
    data["x"], data["y"], data["z"] = g["xyz"].T
    data["f_dc_0"], data["f_dc_1"], data["f_dc_2"] = g["sh0"].T
    data["opacity"] = g["opacity_logit"][:, 0]
    data["scale_0"], data["scale_1"], data["scale_2"] = g["scales_log"].T
    data["rot_0"], data["rot_1"], data["rot_2"], data["rot_3"] = g["rotations"].T

    header = ["ply", "format binary_little_endian 1.0",
              "comment generated by dronemap (TSDF-seeded 3DGS init)",
              f"element vertex {n}"]
    header += [f"property float {nm}" for nm in names]
    header += ["end_header"]
    with open(path, "wb") as fh:
        fh.write(("\n".join(header) + "\n").encode())
        fh.write(data.tobytes())
    log.info("wrote %s (%d gaussians, %.1f MB)", path, n, path.stat().st_size / 1e6)
    return path


def write_splat(path: Path, g: dict) -> Path:
    """Compact ``.splat``: 32 bytes each -- xyz f32, scale f32, rgba u8, quat u8."""
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    n = len(g["xyz"])
    buf = np.zeros((n, 32), np.uint8)

    buf[:, 0:12] = g["xyz"].astype("<f4").view(np.uint8).reshape(n, 12)
    buf[:, 12:24] = g["scales"].astype("<f4").view(np.uint8).reshape(n, 12)
    buf[:, 24:27] = g["rgb"]
    buf[:, 27] = np.uint8(
        np.clip(1.0 / (1.0 + np.exp(-g["opacity_logit"][:, 0])) * 255.0, 0, 255)
    )
    # Quaternions are stored as bytes centred on 128 in this format.
    q = g["rotations"]
    q = q / np.maximum(np.linalg.norm(q, axis=1, keepdims=True), 1e-12)
    buf[:, 28:32] = np.clip(q * 128.0 + 128.0, 0, 255).astype(np.uint8)

    path.write_bytes(buf.tobytes())
    log.info("wrote %s (%d splats, %.1f MB)", path, n, path.stat().st_size / 1e6)
    return path


def export_splats(
    output_dir: Path, basename: str, xyz: np.ndarray, rgb: np.ndarray,
    normals: Optional[np.ndarray] = None, voxel_size: float = 0.04,
) -> dict[str, Path]:
    if len(xyz) == 0:
        log.warning("no surface points; skipping splat export")
        return {}
    g = build_gaussians(xyz, rgb, normals, voxel_size=voxel_size)
    out = Path(output_dir)
    return {
        "splat_ply": write_splat_ply(out / f"{basename}_splat.ply", g),
        "splat": write_splat(out / f"{basename}.splat", g),
    }
