"""permits, flight zone flags

Revision ID: 2277079acb06
Revises: 67ececf28608
Create Date: 2026-07-17 20:18:04.603013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2277079acb06'
down_revision: Union[str, Sequence[str], None] = '67ececf28608'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('drone_id', sa.String(length=36), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('waypoints', sa.JSON(), nullable=False),
    sa.Column('mission_hash', sa.String(length=64), nullable=False),
    sa.Column('zones', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['drone_id'], ['drones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permits_drone_id'), 'permits', ['drone_id'], unique=False)
    op.create_index(op.f('ix_permits_mission_hash'), 'permits', ['mission_hash'], unique=False)
    op.add_column('flights', sa.Column('crossed_orange', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('flights', sa.Column('crossed_red', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flights', 'crossed_red')
    op.drop_column('flights', 'crossed_orange')
    op.drop_index(op.f('ix_permits_mission_hash'), table_name='permits')
    op.drop_index(op.f('ix_permits_drone_id'), table_name='permits')
    op.drop_table('permits')
    # ### end Alembic commands ###
