"""plate_events vehicle colour

Revision ID: 27bf66c11c2c
Revises: 419df6cb4f34
Create Date: 2026-08-06 14:55:14.990658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27bf66c11c2c'
down_revision: Union[str, Sequence[str], None] = '419df6cb4f34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default is required, not cosmetic: these are NOT NULL columns
    # being added to a table that already has rows, and Postgres has no value
    # to put in them without one. Autogenerate omitted it and the migration
    # failed outright on a populated plate_events.
    #
    # Existing rows get "" / 0.0, which reads correctly as "colour was never
    # classified for this vehicle" rather than implying an unknown colour was
    # measured.
    op.add_column('plate_events', sa.Column(
        'vehicle_color', sa.String(length=20), nullable=False, server_default=''))
    op.add_column('plate_events', sa.Column(
        'vehicle_color_conf', sa.Float(), nullable=False, server_default='0'))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plate_events', 'vehicle_color_conf')
    op.drop_column('plate_events', 'vehicle_color')
    # ### end Alembic commands ###
