"""face gallery: persons, person_faces, person_sightings

Revision ID: 419df6cb4f34
Revises: bd47308d11f5
Create Date: 2026-08-06 14:19:42.727913

These are the first tables in this schema holding DURABLE BIOMETRIC IDENTITY
rather than session telemetry. Two consequences for anyone operating the DB:

  * There is no automatic purge. crowd_snapshots die with the session and
    plate_events wait for an operator; persons/person_faces persist until
    explicitly deleted.
  * person_faces.image_path points at the FILESYSTEM. Deleting rows in psql
    orphans the image files — go through persistence.delete_person() /
    clear_face_gallery(), which unlink them. Same trap as plate_events.

person_sightings.person_id is SET NULL rather than CASCADE on purpose: removing
someone from the gallery must not rewrite the log of what the system already
did while they were in it.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '419df6cb4f34'
down_revision: Union[str, Sequence[str], None] = 'bd47308d11f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persons',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persons_active'), 'persons', ['active'], unique=False)
    op.create_index(op.f('ix_persons_name'), 'persons', ['name'], unique=False)
    op.create_table('person_faces',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('person_id', sa.String(length=36), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('embedding', sa.LargeBinary(), nullable=False),
    sa.Column('embedding_dim', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=60), nullable=False),
    sa.Column('det_score', sa.Float(), nullable=False),
    sa.Column('source_filename', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_faces_person_id'), 'person_faces', ['person_id'], unique=False)
    op.create_table('person_sightings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('person_id', sa.String(length=36), nullable=True),
    sa.Column('person_name', sa.String(length=120), nullable=False),
    sa.Column('t', sa.DateTime(timezone=True), nullable=False),
    sa.Column('similarity', sa.Float(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('alt_m', sa.Float(), nullable=True),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_sightings_person_id'), 'person_sightings', ['person_id'], unique=False)
    op.create_index(op.f('ix_person_sightings_session_id'), 'person_sightings', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_person_sightings_session_id'), table_name='person_sightings')
    op.drop_index(op.f('ix_person_sightings_person_id'), table_name='person_sightings')
    op.drop_table('person_sightings')
    op.drop_index(op.f('ix_person_faces_person_id'), table_name='person_faces')
    op.drop_table('person_faces')
    op.drop_index(op.f('ix_persons_name'), table_name='persons')
    op.drop_index(op.f('ix_persons_active'), table_name='persons')
    op.drop_table('persons')
    # ### end Alembic commands ###
