"""zones, flights, flight_samples

Revision ID: 67ececf28608
Revises: 9b063f0fc7ba
Create Date: 2026-07-17 18:48:04.168082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67ececf28608'
down_revision: Union[str, Sequence[str], None] = '9b063f0fc7ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zones',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('zone_class', sa.String(length=10), nullable=False),
    sa.Column('geometry', sa.JSON(), nullable=False),
    sa.Column('floor_m', sa.Float(), nullable=False),
    sa.Column('ceiling_m', sa.Float(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flights',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('drone_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_s', sa.Float(), nullable=False),
    sa.Column('max_alt_m', sa.Float(), nullable=False),
    sa.Column('distance_m', sa.Float(), nullable=False),
    sa.Column('samples_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['drone_id'], ['drones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flights_drone_id'), 'flights', ['drone_id'], unique=False)
    op.create_table('flight_samples',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('flight_id', sa.String(length=36), nullable=False),
    sa.Column('t', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('alt_m', sa.Float(), nullable=False),
    sa.Column('heading_deg', sa.Float(), nullable=False),
    sa.Column('groundspeed_m_s', sa.Float(), nullable=False),
    sa.Column('battery_pct', sa.Float(), nullable=False),
    sa.Column('mode', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flight_samples_flight_id'), 'flight_samples', ['flight_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_flight_samples_flight_id'), table_name='flight_samples')
    op.drop_table('flight_samples')
    op.drop_index(op.f('ix_flights_drone_id'), table_name='flights')
    op.drop_table('flights')
    op.drop_table('zones')
    # ### end Alembic commands ###
