"""crowd and plate tracking tables

Revision ID: bd47308d11f5
Revises: 2277079acb06
Create Date: 2026-07-22 22:36:45.615126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd47308d11f5'
down_revision: Union[str, Sequence[str], None] = '2277079acb06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crowd_alerts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('t', sa.DateTime(timezone=True), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('section_idx', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crowd_alerts_session_id'), 'crowd_alerts', ['session_id'], unique=False)
    op.create_table('crowd_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('t', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_count', sa.Integer(), nullable=False),
    sa.Column('peak_count', sa.Integer(), nullable=False),
    sa.Column('density_level', sa.String(length=10), nullable=False),
    sa.Column('section_counts', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crowd_snapshots_session_id'), 'crowd_snapshots', ['session_id'], unique=False)
    op.create_table('plate_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('plate_text', sa.String(length=20), nullable=False),
    sa.Column('ocr_confidence', sa.Float(), nullable=False),
    sa.Column('vehicle_type', sa.String(length=20), nullable=False),
    sa.Column('vehicle_box', sa.JSON(), nullable=True),
    sa.Column('plate_box', sa.JSON(), nullable=True),
    sa.Column('image_path', sa.String(length=500), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('alt_m', sa.Float(), nullable=True),
    sa.Column('speed_est_kmh', sa.Float(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plate_events_plate_text'), 'plate_events', ['plate_text'], unique=False)
    op.create_index(op.f('ix_plate_events_session_id'), 'plate_events', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plate_events_session_id'), table_name='plate_events')
    op.drop_index(op.f('ix_plate_events_plate_text'), table_name='plate_events')
    op.drop_table('plate_events')
    op.drop_index(op.f('ix_crowd_snapshots_session_id'), table_name='crowd_snapshots')
    op.drop_table('crowd_snapshots')
    op.drop_index(op.f('ix_crowd_alerts_session_id'), table_name='crowd_alerts')
    op.drop_table('crowd_alerts')
    # ### end Alembic commands ###
